# Generated by Django 6.0.3 on 2026-03-13 14:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_task'),
    ]

    operations = [
        migrations.CreateModel(
            name='SearchRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query', models.CharField(max_length=255)),
                ('query_type', models.CharField(choices=[('ip', 'IP'), ('domain', 'Dominio'), ('email', 'Email')], max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('success', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.RemoveField(
            model_name='task',
            name='project',
        ),
        migrations.CreateModel(
            name='IPResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.GenericIPAddressField()),
                ('country', models.CharField(blank=True, max_length=100)),
                ('country_code', models.CharField(blank=True, max_length=4)),
                ('region', models.CharField(blank=True, max_length=100)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('isp', models.CharField(blank=True, max_length=200)),
                ('org', models.CharField(blank=True, max_length=200)),
                ('asn', models.CharField(blank=True, max_length=50)),
                ('timezone', models.CharField(blank=True, max_length=100)),
                ('is_proxy', models.BooleanField(default=False)),
                ('is_hosting', models.BooleanField(default=False)),
                ('record', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ip_result', to='myapp.searchrecord')),
            ],
        ),
        migrations.CreateModel(
            name='EmailResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('breach_count', models.IntegerField(default=0)),
                ('breaches', models.TextField(blank=True)),
                ('record', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='email_result', to='myapp.searchrecord')),
            ],
        ),
        migrations.CreateModel(
            name='DomainResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(max_length=255)),
                ('registrar', models.CharField(blank=True, max_length=255)),
                ('creation_date', models.CharField(blank=True, max_length=100)),
                ('expiration_date', models.CharField(blank=True, max_length=100)),
                ('name_servers', models.TextField(blank=True)),
                ('dns_a', models.TextField(blank=True)),
                ('dns_mx', models.TextField(blank=True)),
                ('dns_ns', models.TextField(blank=True)),
                ('dns_txt', models.TextField(blank=True)),
                ('dns_cname', models.TextField(blank=True)),
                ('record', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='domain_result', to='myapp.searchrecord')),
            ],
        ),
        migrations.DeleteModel(
            name='product',
        ),
        migrations.DeleteModel(
            name='Task',
        ),
    ]
